/*
 * Copyright (c) 2026, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.dopaminesimulator.cards;

import java.util.Locale;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.gameval.SpriteID;

/**
 * Every card in the game, as a constant.
 *
 * <p>The constant name is the card's identity. Its lowercased, hyphenated form
 * prefixed with the set is the id written to save files, so the display name is
 * free to change without orphaning anybody's collection - which was not true
 * while the id was derived from the name. Renaming a constant does break saves,
 * which is the point: it is a visible, deliberate act rather than a side effect
 * of fixing a typo.
 *
 * <p>Referring to a card from a collection or an achievement is a compile-time
 * reference rather than a string that has to be checked by a test.
 *
 * <p>Quest rarity follows the difficulty the game itself gives a quest: Novice
 * and miniquests Common, Intermediate Uncommon, Experienced Rare, Master Epic,
 * Grandmaster Legendary. Slayer rarity follows the slayer level: under 40
 * Common, under 60 Uncommon, under 75 Rare, under 90 Epic, 90 or above
 * Legendary. Diaries follow their tier, Easy through Elite.
 */
@Getter
public enum Cards
{
	ANIMAL_MAGNETISM("Animal Magnetism", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.AVAS_ASSEMBLER, -1),
	ANOTHER_SLICE_OF_H_A_M("Another Slice of H.A.M.", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ANCIENT_GOBLIN_MACE, -1),
	THE_ASCENT_OF_ARCEUUS("The Ascent of Arceuus", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ARCEUUS_ESSENCE_BLOCK_DARK, -1),
	ALFRED_GRIMHAND_S_BARCRAWL("Alfred Grimhand's Barcrawl", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BARCRAWL_CARD, -1),
	BEAR_YOUR_SOUL("Bear Your Soul", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ARCEUUS_SOULBEARER, -1),
	BELOW_ICE_MOUNTAIN("Below Ice Mountain", CardSet.QUESTS, Rarity.COMMON, ItemID.BIM_STEAK_SANDWICH, -1),
	BETWEEN_A_ROCK("Between a Rock...", CardSet.QUESTS, Rarity.RARE, ItemID.DWARF_GOLDROCK_HELMET, -1),
	BIG_CHOMPY_BIRD_HUNTING("Big Chompy Bird Hunting", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.OGRE_BOW, -1),
	BIOHAZARD("Biohazard", CardSet.QUESTS, Rarity.COMMON, ItemID.DISTILLATOR, -1),
	BLACK_KNIGHTS_FORTRESS("Black Knights' Fortress", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.IRON_CHAINBODY, -1),
	BONE_VOYAGE("Bone Voyage", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.FOSSIL_CALCITE, -1),
	CABIN_FEVER("Cabin Fever", CardSet.QUESTS, Rarity.RARE, ItemID.FEVER_PIRACY_BOOK, -1),
	CLIENT_OF_KOUREND("Client of Kourend", CardSet.QUESTS, Rarity.COMMON, ItemID.VEOS_KHAREDSTS_MEMOIRS, -1),
	CLOCK_TOWER("Clock Tower", CardSet.QUESTS, Rarity.COMMON, ItemID.BLACKCOG, -1),
	COLD_WAR("Cold War", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.PENGUIN_MASK, -1),
	CONTACT("Contact!", CardSet.QUESTS, Rarity.RARE, ItemID.CONTACT_KERIS, -1),
	COOK_S_ASSISTANT("Cook's Assistant", CardSet.QUESTS, Rarity.COMMON, ItemID.CAKE, -1),
	THE_CORSAIR_CURSE("The Corsair Curse", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.PIRATE_BANDANA_BROWN, -1),
	CREATURE_OF_FENKENSTRAIN("Creature of Fenkenstrain", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.RING_OF_CHAROS, -1),
	CURSE_OF_THE_EMPTY_LORD("Curse of the Empty Lord", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SECRET_GHOST_TOP, -1),
	DADDY_S_HOME("Daddy's Home", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.POH_SAW, -1),
	DARKNESS_OF_HALLOWVALE("Darkness of Hallowvale", CardSet.QUESTS, Rarity.RARE, ItemID.SILVER_SICKLE_ENCHANTED, -1),
	DEATH_PLATEAU("Death Plateau", CardSet.QUESTS, Rarity.COMMON, ItemID.DEATH_CLIMBINGBOOTS, -1),
	DEATH_TO_THE_DORGESHUUN("Death to the Dorgeshuun", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.DTTD_BONE_CROSSBOW, -1),
	DEMON_SLAYER("Demon Slayer", CardSet.QUESTS, Rarity.COMMON, ItemID.SILVERLIGHT, -1),
	THE_DEPTHS_OF_DESPAIR("The Depths of Despair", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.HOSIDIUSQUEST_ACCORD, -1),
	DESERT_TREASURE_I("Desert Treasure I", CardSet.QUESTS, Rarity.EPIC, ItemID.TRAIL_ANCIENT_STAFF, -1),
	DEVIOUS_MINDS("Devious Minds", CardSet.QUESTS, Rarity.RARE, ItemID.DEVIOUS_BOWSWORD, -1),
	THE_DIG_SITE("The Dig Site", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SPECIMEN_BRUSH, -1),
	DORIC_S_QUEST("Doric's Quest", CardSet.QUESTS, Rarity.COMMON, ItemID.COPPER_ORE, -1),
	DRAGON_SLAYER_I("Dragon Slayer I", CardSet.QUESTS, Rarity.RARE, ItemID.ANTIDRAGONBREATHSHIELD, -1),
	DRAGON_SLAYER_II("Dragon Slayer II", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.MYTHICAL_CAPE, -1),
	DREAM_MENTOR("Dream Mentor", CardSet.QUESTS, Rarity.EPIC, ItemID.DREAM_VIAL_FULL, -1),
	DRUIDIC_RITUAL("Druidic Ritual", CardSet.QUESTS, Rarity.COMMON, ItemID.GUAM_LEAF, -1),
	DWARF_CANNON("Dwarf Cannon", CardSet.QUESTS, Rarity.COMMON, ItemID.MCANNONTOOLKIT, -1),
	EADGAR_S_RUSE("Eadgar's Ruse", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.EADGAR_GOUTWEED_HERB, -1),
	EAGLES_PEAK("Eagles' Peak", CardSet.QUESTS, Rarity.COMMON, ItemID.HUNTING_FERRET, -1),
	ELEMENTAL_WORKSHOP_I("Elemental Workshop I", CardSet.QUESTS, Rarity.COMMON, ItemID.ELEMENTAL_SHIELD, -1),
	ELEMENTAL_WORKSHOP_II("Elemental Workshop II", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ELEM_MIND_HELM, -1),
	ENAKHRA_S_LAMENT("Enakhra's Lament", CardSet.QUESTS, Rarity.RARE, ItemID.CAMULET, -1),
	THE_ENCHANTED_KEY("The Enchanted Key", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.MAKINGHISTORY_KEY, -1),
	ENLIGHTENED_JOURNEY("Enlightened Journey", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ZEP_TEST_BALLOON, -1),
	ENTER_THE_ABYSS("Enter the Abyss", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.RCU_POUCH_SMALL, -1),
	ERNEST_THE_CHICKEN("Ernest the Chicken", CardSet.QUESTS, Rarity.COMMON, ItemID.RAW_CHICKEN, -1),
	THE_EYES_OF_GLOUPHRIE("The Eyes of Glouphrie", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.EYEGLO_BLUE_CIRCLE, -1),
	FAIRYTALE_I_GROWING_PAINS("Fairytale I - Growing Pains", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.FAIRY_ENCHANTED_SECATEURS, -1),
	FAIRYTALE_II_CURE_A_QUEEN("Fairytale II - Cure a Queen", CardSet.QUESTS, Rarity.RARE, ItemID.FAIRYTALE2_NUFFS_CERTIFICATE, -1),
	FAMILY_CREST("Family Crest", CardSet.QUESTS, Rarity.RARE, ItemID.FAMILY_CREST, -1),
	FAMILY_PEST("Family Pest", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GAUNTLETS_OF_CHAOS, -1),
	THE_FEUD("The Feud", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BLACKJACK_OAK, -1),
	FIGHT_ARENA("Fight Arena", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.KHAZARD_PLATEMAIL, -1),
	FISHING_CONTEST("Fishing Contest", CardSet.QUESTS, Rarity.COMMON, ItemID.HEMENSTER_FISHING_TROPHY, -1),
	FORGETTABLE_TALE("Forgettable Tale...", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.DWARVEN_STOUT, -1),
	THE_FORSAKEN_TOWER("The Forsaken Tower", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.LOVAQUEST_HAMMER, -1),
	THE_FREMENNIK_EXILES("The Fremennik Exiles", CardSet.QUESTS, Rarity.EPIC, ItemID.NEITIZNOT_FACEGUARD, -1),
	THE_FREMENNIK_ISLES("The Fremennik Isles", CardSet.QUESTS, Rarity.RARE, ItemID.FRIS_KINGLY_HELM, -1),
	THE_FREMENNIK_TRIALS("The Fremennik Trials", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.VIKING_ENCHANTED_STRUNG_LYRE, -1),
	GARDEN_OF_TRANQUILLITY("Garden of Tranquillity", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.RING_OF_CHAROS_UNLOCKED, -1),
	THE_GENERAL_S_SHADOW("The General's Shadow", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SHADOW_MAJ_SHADOW_SWORD, -1),
	GERTRUDE_S_CAT("Gertrude's Cat", CardSet.QUESTS, Rarity.COMMON, ItemID.LAZYCATOBJECT_BROWN, -1),
	GETTING_AHEAD("Getting Ahead", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GA_FURHEAD, -1),
	GHOSTS_AHOY("Ghosts Ahoy", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ECTOPHIAL, -1),
	THE_GIANT_DWARF("The Giant Dwarf", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.POH_UNFRAMED_PAINTING_GIANTDWARF, -1),
	GOBLIN_DIPLOMACY("Goblin Diplomacy", CardSet.QUESTS, Rarity.COMMON, ItemID.GOBLIN_ARMOUR, -1),
	THE_GOLEM("The Golem", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GOLEM_STATUETTE, -1),
	THE_GRAND_TREE("The Grand Tree", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GRANDTREE_DACONIAROCK, -1),
	THE_GREAT_BRAIN_ROBBERY("The Great Brain Robbery", CardSet.QUESTS, Rarity.RARE, ItemID.BRAIN_ANCHOR, -1),
	GRIM_TALES("Grim Tales", CardSet.QUESTS, Rarity.EPIC, ItemID.GRIM_WEAR_HELMET, -1),
	THE_HAND_IN_THE_SAND("The Hand in the Sand", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.HANDSAND_SANDYHAND, -1),
	HAUNTED_MINE("Haunted Mine", CardSet.QUESTS, Rarity.RARE, ItemID.CRYSTALSHARD_NECKLACE, -1),
	HAZEEL_CULT("Hazeel Cult", CardSet.QUESTS, Rarity.COMMON, ItemID.CARNILLEAN_ARMOUR, -1),
	HEROES_QUEST("Heroes' Quest", CardSet.QUESTS, Rarity.RARE, ItemID.DRAGON_BATTLEAXE, -1),
	HOLY_GRAIL("Holy Grail", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.HOLY_GRAIL, -1),
	HORROR_FROM_THE_DEEP("Horror from the Deep", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.HORROR_CASKET, -1),
	ICTHLARIN_S_LITTLE_HELPER("Icthlarin's Little Helper", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ICS_LITTLE_AMULET_OF_CATSPEAK, -1),
	IMP_CATCHER("Imp Catcher", CardSet.QUESTS, Rarity.COMMON, ItemID.AMULET_OF_ACCURACY, -1),
	IN_AID_OF_THE_MYREQUE("In Aid of the Myreque", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BURGH_ROD_COMMAND_FINAL_10, -1),
	IN_SEARCH_OF_KNOWLEDGE("In Search of Knowledge", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ARCEUUS_LIBRARY_REWARD, -1),
	IN_SEARCH_OF_THE_MYREQUE("In Search of the Myreque", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SILVER_SICKLE, -1),
	JUNGLE_POTION("Jungle Potion", CardSet.QUESTS, Rarity.COMMON, ItemID.SNAKE_WEED, -1),
	A_KINGDOM_DIVIDED("A Kingdom Divided", CardSet.QUESTS, Rarity.RARE, ItemID.AKD_ROSES_DUMMY, -1),
	KING_S_RANSOM("King's Ransom", CardSet.QUESTS, Rarity.RARE, ItemID.KR_CLUE_ARMOUR, -1),
	THE_KNIGHT_S_SWORD("The Knight's Sword", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.FALADIAN_SWORD, -1),
	LAIR_OF_TARN_RAZORLOR("Lair of Tarn Razorlor", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.LOTR_CRYSTALSHARD_NECKLACE_UPGRADE, -1),
	LEGENDS_QUEST("Legends' Quest", CardSet.QUESTS, Rarity.EPIC, ItemID.CAPE_OF_LEGENDS, -1),
	LOST_CITY("Lost City", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.DRAMEN_STAFF, -1),
	THE_LOST_TRIBE("The Lost Tribe", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.LOST_TRIBE_BROOCH, -1),
	LUNAR_DIPLOMACY("Lunar Diplomacy", CardSet.QUESTS, Rarity.RARE, ItemID.LUNAR_MOONCLAN_LIMINAL_STAFF, -1),
	MAGE_ARENA_I("Mage Arena I", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SARADOMIN_CAPE, -1),
	MAGE_ARENA_II("Mage Arena II", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.MA2_SARADOMIN_CAPE, -1),
	MAKING_FRIENDS_WITH_MY_ARM("Making Friends with My Arm", CardSet.QUESTS, Rarity.EPIC, ItemID.MY2ARM_COFFIN, -1),
	MAKING_HISTORY("Making History", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.MAKINGHISTORY_KEY, -1),
	MERLIN_S_CRYSTAL("Merlin's Crystal", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.EXCALIBUR, -1),
	MISTHALIN_MYSTERY("Misthalin Mystery", CardSet.QUESTS, Rarity.COMMON, ItemID.MACRO_QUIZ_MYSTERY_BOX, -1),
	MONKEY_MADNESS_I("Monkey Madness I", CardSet.QUESTS, Rarity.EPIC, ItemID.DRAGON_SCIMITAR, -1),
	MONKEY_MADNESS_II("Monkey Madness II", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.HEAVY_BALLISTA, -1),
	MONK_S_FRIEND("Monk's Friend", CardSet.QUESTS, Rarity.COMMON, ItemID.MONKROBETOP, -1),
	MOUNTAIN_DAUGHTER("Mountain Daughter", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.MDAUGHTER_BEAR_HELMET, -1),
	MOURNING_S_END_PART_I("Mourning's End Part I", CardSet.QUESTS, Rarity.EPIC, ItemID.MOURNING_MOURNER_TOP, -1),
	MOURNING_S_END_PART_II("Mourning's End Part II", CardSet.QUESTS, Rarity.EPIC, ItemID.DEATH_TALISMAN, -1),
	MURDER_MYSTERY("Murder Mystery", CardSet.QUESTS, Rarity.COMMON, ItemID.MURDERNECKLACE, -1),
	MY_ARM_S_BIG_ADVENTURE("My Arm's Big Adventure", CardSet.QUESTS, Rarity.RARE, ItemID.MYARM_HARDYTUBERS, -1),
	NATURE_SPIRIT("Nature Spirit", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SILVER_SICKLE_BLESSED, -1),
	A_NIGHT_AT_THE_THEATRE("A Night at the Theatre", CardSet.QUESTS, Rarity.EPIC, ItemID.VERZIK_SPECIAL_WEAPON, -1),
	OBSERVATORY_QUEST("Observatory Quest", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TELESCOPE_DUMMY, -1),
	OLAF_S_QUEST("Olaf's Quest", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.OLAF2_GATE_KEY_1, -1),
	ONE_SMALL_FAVOUR("One Small Favour", CardSet.QUESTS, Rarity.RARE, ItemID.FAVOUR_KEY_RING, -1),
	PIRATE_S_TREASURE("Pirate's Treasure", CardSet.QUESTS, Rarity.COMMON, ItemID.CASKET, -1),
	PLAGUE_CITY("Plague City", CardSet.QUESTS, Rarity.COMMON, ItemID.GASMASK, -1),
	A_PORCINE_OF_INTEREST("A Porcine of Interest", CardSet.QUESTS, Rarity.COMMON, ItemID.PORCINE_SOURHOG_TROPHY, -1),
	PRIEST_IN_PERIL("Priest in Peril", CardSet.QUESTS, Rarity.COMMON, ItemID.DAGGER_WOLFBANE, -1),
	PRINCE_ALI_RESCUE("Prince Ali Rescue", CardSet.QUESTS, Rarity.COMMON, ItemID.SKINPASTE, -1),
	THE_QUEEN_OF_THIEVES("The Queen of Thieves", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.VEOS_MEMOIRS_PISC_PAGE, -1),
	RAG_AND_BONE_MAN_I("Rag and Bone Man I", CardSet.QUESTS, Rarity.COMMON, ItemID.RAG_POLISHED_GOBLIN_BONE, -1),
	RAG_AND_BONE_MAN_II("Rag and Bone Man II", CardSet.QUESTS, Rarity.RARE, ItemID.RAG_BONESACK, -1),
	RATCATCHERS("Ratcatchers", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SNAKE_FLUTE, -1),
	RECIPE_FOR_DISASTER("Recipe for Disaster", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.HUNDRED_GAUNTLETS_LEVEL_10, -1),
	RECRUITMENT_DRIVE("Recruitment Drive", CardSet.QUESTS, Rarity.COMMON, ItemID.BASIC_TK_HELM, -1),
	REGICIDE("Regicide", CardSet.QUESTS, Rarity.RARE, ItemID.DRAGON_HALBERD, -1),
	THE_RESTLESS_GHOST("The Restless Ghost", CardSet.QUESTS, Rarity.COMMON, ItemID.AMULET_OF_GHOSTSPEAK, -1),
	ROMEO_JULIET("Romeo & Juliet", CardSet.QUESTS, Rarity.COMMON, ItemID.CADAVA, -1),
	ROVING_ELVES("Roving Elves", CardSet.QUESTS, Rarity.RARE, ItemID.CRYSTAL_BOW, -1),
	ROYAL_TROUBLE("Royal Trouble", CardSet.QUESTS, Rarity.RARE, ItemID.ROYAL_BOX, -1),
	RUM_DEAL("Rum Deal", CardSet.QUESTS, Rarity.RARE, ItemID.DEAL_WRENCH_BLESSED, -1),
	RUNE_MYSTERIES("Rune Mysteries", CardSet.QUESTS, Rarity.COMMON, ItemID.AIR_TALISMAN, -1),
	SCORPION_CATCHER("Scorpion Catcher", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SCORPIONCAGEFULL, -1),
	SEA_SLUG("Sea Slug", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SLUG2_SEASLUG_YOUNG, -1),
	SHADES_OF_MORT_TON("Shades of Mort'ton", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.FLAMTAER_HAMMER, -1),
	SHADOW_OF_THE_STORM("Shadow of the Storm", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.DARKLIGHT, -1),
	SHEEP_HERDER("Sheep Herder", CardSet.QUESTS, Rarity.COMMON, ItemID.PLAGUE_JACKET, -1),
	SHEEP_SHEARER("Sheep Shearer", CardSet.QUESTS, Rarity.COMMON, ItemID.BALL_OF_WOOL, -1),
	SHIELD_OF_ARRAV("Shield of Arrav", CardSet.QUESTS, Rarity.COMMON, ItemID.THE_SHIELD_OF_ARRAV, -1),
	SHILO_VILLAGE("Shilo Village", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.MOSOL_WAMPUM_BELT, -1),
	SINS_OF_THE_FATHER("Sins of the Father", CardSet.QUESTS, Rarity.EPIC, ItemID.BLISTERWOOD_FLAIL, -1),
	SKIPPY_AND_THE_MOGRES("Skippy and the Mogres", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_MOGRE, -1),
	THE_SLUG_MENACE("The Slug Menace", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BASIC_TK_RANK2_HELM, -1),
	SONG_OF_THE_ELVES("Song of the Elves", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.BLADE_OF_SAELDOR, -1),
	A_SOUL_S_BANE("A Soul's Bane", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SOULBANE_ZAROS_SPEAR, -1),
	SPIRITS_OF_THE_ELID("Spirits of the Elid", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ELID_STATUETTE, -1),
	SWAN_SONG("Swan Song", CardSet.QUESTS, Rarity.EPIC, ItemID.MONKFISH, -1),
	TAI_BWO_WANNAI_TRIO("Tai Bwo Wannai Trio", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TBWT_RAW_KARAMBWAN, -1),
	A_TAIL_OF_TWO_CATS("A Tail of Two Cats", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TWOCATS_AMULETOFCATSPEAK, -1),
	TALE_OF_THE_RIGHTEOUS("Tale of the Righteous", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SHAYZIENQUEST_CRYSTAL_DUMMY, -1),
	A_TASTE_OF_HOPE("A Taste of Hope", CardSet.QUESTS, Rarity.RARE, ItemID.IVANDIS_FLAIL, -1),
	TEARS_OF_GUTHIX("Tears of Guthix", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TOG_BOWL, -1),
	TEMPLE_OF_IKOV("Temple of Ikov", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.IKOV_STAFFOFARMARDYL, -1),
	THRONE_OF_MISCELLANIA("Throne of Miscellania", CardSet.QUESTS, Rarity.RARE, ItemID.MISC_TREATY, -1),
	THE_TOURIST_TRAP("The Tourist Trap", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.DESERT_SHIRT, -1),
	TOWER_OF_LIFE("Tower of Life", CardSet.QUESTS, Rarity.COMMON, ItemID.TOL_PLAYER_CONSTRUCTION_HARDHAT, -1),
	TREE_GNOME_VILLAGE("Tree Gnome Village", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GNOME_AMULET, -1),
	TRIBAL_TOTEM("Tribal Totem", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TRIBAL_TOTEM, -1),
	TROLL_ROMANCE("Troll Romance", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TROLLROMANCE_TOBOGGON, -1),
	TROLL_STRONGHOLD("Troll Stronghold", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TROLL_KEY_PRISON, -1),
	UNDERGROUND_PASS("Underground Pass", CardSet.QUESTS, Rarity.RARE, ItemID.IBANSTAFF, -1),
	VAMPYRE_SLAYER("Vampyre Slayer", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.STAKE, -1),
	WANTED("Wanted!", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.WANTED_SOLUS_TROPHY, -1),
	WATCHTOWER("Watchtower", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.OGRERELIC, -1),
	WATERFALL_QUEST("Waterfall Quest", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GLARIALS_AMULET_WATERFALL_QUEST, -1),
	WHAT_LIES_BELOW("What Lies Below", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SUROK_RING, -1),
	WITCH_S_HOUSE("Witch's House", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BALL, -1),
	WITCH_S_POTION("Witch's Potion", CardSet.QUESTS, Rarity.COMMON, ItemID.EYE_OF_NEWT, -1),
	X_MARKS_THE_SPOT("X Marks the Spot", CardSet.QUESTS, Rarity.COMMON, ItemID.SPADE, -1),
	ZOGRE_FLESH_EATERS("Zogre Flesh Eaters", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ZOGRE_BOW, -1),
	THE_FROZEN_DOOR("The Frozen Door", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.NEX_FROZEN_KEY, -1),
	LAND_OF_THE_GOBLINS("Land of the Goblins", CardSet.QUESTS, Rarity.RARE, ItemID.LOTG_3DOSEGOBLIN, -1),
	HOPESPEAR_S_WILL("Hopespear's Will", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.LOTG_BONE_HIGHPRIEST5, -1),
	TEMPLE_OF_THE_EYE("Temple of the Eye", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TOTE_AMULET, -1),
	BENEATH_CURSED_SANDS("Beneath Cursed Sands", CardSet.QUESTS, Rarity.EPIC, ItemID.KERIS_PARTISAN, -1),
	SLEEPING_GIANTS("Sleeping Giants", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.GIANTS_FOUNDRY_COLOSSAL_BLADE, -1),
	THE_GARDEN_OF_DEATH("The Garden of Death", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.TGOD_TABLET_1, -1),
	INTO_THE_TOMBS("Into the Tombs", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.OSMUMTENS_FANG, -1),
	RECIPE_FOR_DISASTER_ANOTHER_COOK_S_QUEST("Recipe for Disaster - Another Cook's Quest", CardSet.QUESTS, Rarity.COMMON, ItemID.EGG, -1),
	RECIPE_FOR_DISASTER_MOUNTAIN_DWARF("Recipe for Disaster - Mountain Dwarf", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ROCKCAKE, -1),
	RECIPE_FOR_DISASTER_WARTFACE_BENTNOZE("Recipe for Disaster - Wartface & Bentnoze", CardSet.QUESTS, Rarity.UNCOMMON, ItemID._100GOBLIN_COMPROMISE_MUSH, -1),
	RECIPE_FOR_DISASTER_PIRATE_PETE("Recipe for Disaster - Pirate Pete", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.HUNDRED_PIRATE_FISHCAKE, -1),
	RECIPE_FOR_DISASTER_LUMBRIDGE_GUIDE("Recipe for Disaster - Lumbridge Guide", CardSet.QUESTS, Rarity.RARE, ItemID._100GUIDE_GUIDECAKE, -1),
	RECIPE_FOR_DISASTER_EVIL_DAVE("Recipe for Disaster - Evil Dave", CardSet.QUESTS, Rarity.RARE, ItemID.HUNDRED_DAVE_STEW, -1),
	RECIPE_FOR_DISASTER_SKRACH_UGLOGWEE("Recipe for Disaster - Skrach Uglogwee", CardSet.QUESTS, Rarity.RARE, ItemID._100_JUBBLY_MEAT_COOKED, -1),
	RECIPE_FOR_DISASTER_SIR_AMIK_VARZE("Recipe for Disaster - Sir Amik Varze", CardSet.QUESTS, Rarity.EPIC, ItemID.CHICKENQUEST_EVIL_CHICKEN_EGG, -1),
	RECIPE_FOR_DISASTER_KING_AWOWOGEI("Recipe for Disaster - King Awowogei", CardSet.QUESTS, Rarity.EPIC, ItemID.HUNDRED_ILM_COOKED_STUFFED_SNAKE, -1),
	RECIPE_FOR_DISASTER_CULINAROMANCER("Recipe for Disaster - Culinaromancer", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.HUNDRED_GAUNTLETS_LEVEL_10, -1),
	SECRETS_OF_THE_NORTH("Secrets of the North", CardSet.QUESTS, Rarity.EPIC, ItemID.VENATOR_BOW, -1),
	DESERT_TREASURE_II_THE_FALLEN_EMPIRE("Desert Treasure II - The Fallen Empire", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.DT2_ELDER_HORN_DUMMY, -1),
	HIS_FAITHFUL_SERVANTS("His Faithful Servants", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BARROWS_BOOK_HISTORY, -1),
	THE_PATH_OF_GLOUPHRIE("The Path of Glouphrie", CardSet.QUESTS, Rarity.RARE, ItemID.CRYSTAL_CHIME, -1),
	CHILDREN_OF_THE_SUN("Children of the Sun", CardSet.QUESTS, Rarity.COMMON, ItemID.VARLAMORE_JAGUAR_FUR, -1),
	BARBARIAN_TRAINING("Barbarian Training", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.BRUT_FISHING_ROD, -1),
	DEFENDER_OF_VARROCK("Defender of Varrock", CardSet.QUESTS, Rarity.RARE, ItemID.DOV_SHIELD_OF_ARRAV, -1),
	WHILE_GUTHIX_SLEEPS("While Guthix Sleeps", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.WGS_STONE_OF_JAS_DUMMY_ITEM, -1),
	TWILIGHT_S_PROMISE("Twilight's Promise", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.VMQ2_CREST, -1),
	AT_FIRST_LIGHT("At First Light", CardSet.QUESTS, Rarity.COMMON, ItemID.GB_MOSS_ESSENCE, -1),
	PERILOUS_MOONS("Perilous Moons", CardSet.QUESTS, Rarity.EPIC, ItemID.PMOON_ICOSAHEDRON, -1),
	THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE("The Ribbiting Tale of a Lily Pad Labour Dispute", CardSet.QUESTS, Rarity.COMMON, ItemID.ORANGE, -1),
	THE_HEART_OF_DARKNESS("The Heart of Darkness", CardSet.QUESTS, Rarity.RARE, ItemID.VMQ3_CULTIST_ROBE_TOP, -1),
	DEATH_ON_THE_ISLE("Death on the Isle", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.DOTI_CASEFILE, -1),
	MEAT_AND_GREET("Meat and Greet", CardSet.QUESTS, Rarity.RARE, ItemID.COOKED_MEAT_UNDEAD, -1),
	ETHICALLY_ACQUIRED_ANTIQUITIES("Ethically Acquired Antiquities", CardSet.QUESTS, Rarity.COMMON, ItemID.VM_MUSEUM_MAP, -1),
	THE_CURSE_OF_ARRAV("The Curse of Arrav", CardSet.QUESTS, Rarity.EPIC, ItemID.COA_CANOPIC_JAR_COMPLETE, -1),
	THE_FINAL_DAWN("The Final Dawn", CardSet.QUESTS, Rarity.EPIC, ItemID.ARKAN_BLADE, -1),
	SHADOWS_OF_CUSTODIA("Shadows of Custodia", CardSet.QUESTS, Rarity.RARE, ItemID.CUSTODIAN_ANTLER_GUARD, -1),
	SCRAMBLED("Scrambled!", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.SCRAMBLED_EGG, -1),
	VALE_TOTEMS("Vale Totems", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.ENT_TOTEMS_LOOT, -1),
	PANDEMONIUM("Pandemonium", CardSet.QUESTS, Rarity.COMMON, ItemID.SAILING_CHARTING_SPYGLASS, -1),
	PRYING_TIMES("Prying Times", CardSet.QUESTS, Rarity.UNCOMMON, ItemID.PRYING_TIMES_CARGO_CRATE, -1),
	CURRENT_AFFAIRS("Current Affairs", CardSet.QUESTS, Rarity.COMMON, ItemID.DUMMY_CHARTING_DUCK, -1),
	TROUBLED_TORTUGANS("Troubled Tortugans", CardSet.QUESTS, Rarity.RARE, ItemID.TORTUGAN_SHIELD, -1),
	THE_RED_REEF("The Red Reef", CardSet.QUESTS, Rarity.RARE, ItemID.TRR_RED_CORAL, -1),
	LEARNING_THE_ROPES("Learning the Ropes", CardSet.QUESTS, Rarity.COMMON, ItemID.BURNT_SHRIMP, -1),
	THE_IDES_OF_MILK("The Ides of Milk", CardSet.QUESTS, Rarity.COMMON, ItemID.COWQUEST_MILK_SAMPLE_1, -1),
	THE_BLOOD_MOON_RISES("The Blood Moon Rises", CardSet.QUESTS, Rarity.LEGENDARY, ItemID.HALLOWED_FLAIL, -1),
	ATTACK("Attack", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.ATTACK),
	DEFENCE("Defence", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.DEFENCE),
	STRENGTH("Strength", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.STRENGTH),
	HITPOINTS("Hitpoints", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.HITPOINTS),
	RANGED("Ranged", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.RANGED),
	PRAYER("Prayer", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.PRAYER),
	MAGIC("Magic", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.MAGIC),
	COOKING("Cooking", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.COOKING),
	WOODCUTTING("Woodcutting", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.WOODCUTTING),
	FLETCHING("Fletching", CardSet.SKILLS, Rarity.UNCOMMON, -1, SpriteID.Staticons.FLETCHING),
	FISHING("Fishing", CardSet.SKILLS, Rarity.UNCOMMON, -1, SpriteID.Staticons.FISHING),
	FIREMAKING("Firemaking", CardSet.SKILLS, Rarity.COMMON, -1, SpriteID.Staticons.FIREMAKING),
	CRAFTING("Crafting", CardSet.SKILLS, Rarity.UNCOMMON, -1, SpriteID.Staticons.CRAFTING),
	SMITHING("Smithing", CardSet.SKILLS, Rarity.UNCOMMON, -1, SpriteID.Staticons.SMITHING),
	MINING("Mining", CardSet.SKILLS, Rarity.UNCOMMON, -1, SpriteID.Staticons.MINING),
	HERBLORE("Herblore", CardSet.SKILLS, Rarity.RARE, -1, SpriteID.Staticons.HERBLORE),
	AGILITY("Agility", CardSet.SKILLS, Rarity.EPIC, -1, SpriteID.Staticons.AGILITY),
	THIEVING("Thieving", CardSet.SKILLS, Rarity.UNCOMMON, -1, SpriteID.Staticons.THIEVING),
	SLAYER("Slayer", CardSet.SKILLS, Rarity.RARE, -1, SpriteID.Staticons2.SLAYER),
	FARMING("Farming", CardSet.SKILLS, Rarity.RARE, -1, SpriteID.Staticons2.FARMING),
	RUNECRAFT("Runecraft", CardSet.SKILLS, Rarity.LEGENDARY, -1, SpriteID.Staticons2.RUNECRAFT),
	HUNTER("Hunter", CardSet.SKILLS, Rarity.RARE, -1, SpriteID.Staticons2.HUNTER),
	CONSTRUCTION("Construction", CardSet.SKILLS, Rarity.EPIC, -1, SpriteID.Staticons2.CONSTRUCTION),
	SAILING("Sailing", CardSet.SKILLS, Rarity.RARE, -1, SpriteID.Staticons2.SAILING),
	OBOR("Obor", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.OBOR),
	BRYOPHYTA("Bryophyta", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.BRYOPHYTA),
	GIANT_MOLE("Giant Mole", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.GIANT_MOLE),
	TEMPOROSS("Tempoross", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.TEMPOROSS),
	WINTERTODT("Wintertodt", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.WINTERTODT),
	BARROWS("Barrows", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.BARROWS_CHESTS),
	SARACHNIS("Sarachnis", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.SARACHNIS),
	HESPORI("Hespori", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.HESPORI),
	SCURRIUS("Scurrius", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.SCURRIUS),
	DERANGED_ARCHAEOLOGIST("Deranged Archaeologist", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.DERANGED_ARCHAEOLOGIST),
	CHAOS_FANATIC("Chaos Fanatic", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.CHAOS_FANATIC),
	CRAZY_ARCHAEOLOGIST("Crazy Archaeologist", CardSet.BOSSES, Rarity.COMMON, -1, SpriteID.IconBoss25x25.CRAZY_ARCHAEOLOGIST),
	KALPHITE_QUEEN("Kalphite Queen", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.KALPHITE_QUEEN),
	KING_BLACK_DRAGON("King Black Dragon", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.KING_BLACK_DRAGON),
	SKOTIZO("Skotizo", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.SKOTIZO),
	ZALCANO("Zalcano", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.ZALCANO),
	KRAKEN("Kraken", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.KRAKEN),
	GROTESQUE_GUARDIANS("Grotesque Guardians", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.GROTESQUE_GUARDIANS),
	SCORPIA("Scorpia", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.SCORPIA),
	CHAOS_ELEMENTAL("Chaos Elemental", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.CHAOS_ELEMENTAL),
	DAGANNOTH_REX("Dagannoth Rex", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.DAGANNOTH_REX),
	DAGANNOTH_PRIME("Dagannoth Prime", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.DAGANNOTH_PRIME),
	DAGANNOTH_SUPREME("Dagannoth Supreme", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.DAGANNOTH_SUPREME),
	MIMIC("Mimic", CardSet.BOSSES, Rarity.UNCOMMON, -1, SpriteID.IconBoss25x25.MIMIC),
	ZULRAH("Zulrah", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.ZULRAH),
	VORKATH("Vorkath", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.VORKATH),
	ABYSSAL_SIRE("Abyssal Sire", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.ABYSSAL_SIRE),
	THERMONUCLEAR_SMOKE_DEVIL("Thermonuclear Smoke Devil", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.THERMONUCLEAR_SMOKE_DEVIL),
	CERBERUS("Cerberus", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.CERBERUS),
	GENERAL_GRAARDOR("General Graardor", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.GENERAL_GRAARDOR),
	K_RIL_TSUTSAROTH("K'ril Tsutsaroth", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.KRIL_TSUTSAROTH),
	COMMANDER_ZILYANA("Commander Zilyana", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.COMMANDER_ZILYANA),
	KREE_ARRA("Kree'arra", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.KREEARRA),
	ALCHEMICAL_HYDRA("Alchemical Hydra", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.ALCHEMICAL_HYDRA),
	CALLISTO("Callisto", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.ARTIO_CALLISTO),
	VET_ION("Vet'ion", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.CALVARION_VETION),
	VENENATIS("Venenatis", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.SPINDEL_VENENATIS),
	THE_GAUNTLET("The Gauntlet", CardSet.BOSSES, Rarity.RARE, -1, SpriteID.IconBoss25x25.THE_GAUNTLET),
	CORPOREAL_BEAST("Corporeal Beast", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.CORPOREAL_BEAST),
	THE_NIGHTMARE("The Nightmare", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.NIGHTMARE),
	PHANTOM_MUSPAH("Phantom Muspah", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.PHANTOM_MUSPAH),
	NEX("Nex", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.NEX),
	DUKE_SUCELLUS("Duke Sucellus", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.DUKE_SUCELLUS),
	THE_LEVIATHAN("The Leviathan", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.THE_LEVIATHAN),
	THE_WHISPERER("The Whisperer", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.THE_WHISPERER),
	VARDORVIS("Vardorvis", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.VARDORVIS),
	ARAXXOR("Araxxor", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.ARAXXOR),
	THE_CORRUPTED_GAUNTLET("The Corrupted Gauntlet", CardSet.BOSSES, Rarity.EPIC, -1, SpriteID.IconBoss25x25.THE_CORRUPTED_GAUNTLET),
	CHAMBERS_OF_XERIC("Chambers of Xeric", CardSet.BOSSES, Rarity.LEGENDARY, -1, SpriteID.IconBoss25x25.CHAMBERS_OF_XERIC),
	CHAMBERS_OF_XERIC_CHALLENGE_MODE("Chambers of Xeric: Challenge Mode", CardSet.BOSSES, Rarity.LEGENDARY, ItemID.TWISTED_BOW, -1),
	THEATRE_OF_BLOOD("Theatre of Blood", CardSet.BOSSES, Rarity.LEGENDARY, -1, SpriteID.IconBoss25x25.THEATRE_OF_BLOOD),
	TOMBS_OF_AMASCUT("Tombs of Amascut", CardSet.BOSSES, Rarity.LEGENDARY, -1, SpriteID.IconBoss25x25.TOMBS_OF_AMASCUT),
	YAMA("Yama", CardSet.BOSSES, Rarity.LEGENDARY, -1, SpriteID.IconBoss25x25.YAMA),
	ROYAL_TITANS("Royal Titans", CardSet.BOSSES, Rarity.LEGENDARY, -1, SpriteID.IconBoss25x25.ROYAL_TITANS),
	LOGS("Logs", CardSet.ITEMS, Rarity.COMMON, ItemID.LOGS, -1),
	OAK_LOGS("Oak Logs", CardSet.ITEMS, Rarity.COMMON, ItemID.OAK_LOGS, -1),
	WILLOW_LOGS("Willow Logs", CardSet.ITEMS, Rarity.COMMON, ItemID.WILLOW_LOGS, -1),
	MAPLE_LOGS("Maple Logs", CardSet.ITEMS, Rarity.COMMON, ItemID.MAPLE_LOGS, -1),
	COPPER_ORE("Copper Ore", CardSet.ITEMS, Rarity.COMMON, ItemID.COPPER_ORE, -1),
	TIN_ORE("Tin Ore", CardSet.ITEMS, Rarity.COMMON, ItemID.TIN_ORE, -1),
	IRON_ORE("Iron Ore", CardSet.ITEMS, Rarity.COMMON, ItemID.IRON_ORE, -1),
	COAL("Coal", CardSet.ITEMS, Rarity.COMMON, ItemID.COAL, -1),
	RAW_TROUT("Raw Trout", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_TROUT, -1),
	RAW_SALMON("Raw Salmon", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_SALMON, -1),
	BONES("Bones", CardSet.ITEMS, Rarity.COMMON, ItemID.BONES, -1),
	CABBAGE("Cabbage", CardSet.ITEMS, Rarity.COMMON, ItemID.CABBAGE, -1),
	BREAD("Bread", CardSet.ITEMS, Rarity.COMMON, ItemID.BREAD, -1),
	TINDERBOX("Tinderbox", CardSet.ITEMS, Rarity.COMMON, ItemID.TINDERBOX, -1),
	ROPE("Rope", CardSet.ITEMS, Rarity.COMMON, ItemID.ROPE, -1),
	HAMMER("Hammer", CardSet.ITEMS, Rarity.COMMON, ItemID.HAMMER, -1),
	CHISEL("Chisel", CardSet.ITEMS, Rarity.COMMON, ItemID.CHISEL, -1),
	KNIFE("Knife", CardSet.ITEMS, Rarity.COMMON, ItemID.KNIFE, -1),
	SPADE("Spade", CardSet.ITEMS, Rarity.COMMON, ItemID.SPADE, -1),
	FEATHER("Feather", CardSet.ITEMS, Rarity.COMMON, ItemID.FEATHER, -1),
	FLAX("Flax", CardSet.ITEMS, Rarity.COMMON, ItemID.FLAX, -1),
	GRAIN("Grain", CardSet.ITEMS, Rarity.COMMON, ItemID.GRAIN, -1),
	BUCKET_OF_SAND("Bucket of Sand", CardSet.ITEMS, Rarity.COMMON, ItemID.BUCKET_SAND, -1),
	EMPTY_VIAL("Empty Vial", CardSet.ITEMS, Rarity.COMMON, ItemID.VIAL_EMPTY, -1),
	CAKE("Cake", CardSet.ITEMS, Rarity.COMMON, ItemID.CAKE, -1),
	BRONZE_DAGGER("Bronze Dagger", CardSet.ITEMS, Rarity.COMMON, ItemID.BRONZE_DAGGER, -1),
	BRONZE_SWORD("Bronze Sword", CardSet.ITEMS, Rarity.COMMON, ItemID.BRONZE_SWORD, -1),
	GUAM_LEAF("Guam Leaf", CardSet.ITEMS, Rarity.COMMON, ItemID.GUAM_LEAF, -1),
	BIG_BONES("Big Bones", CardSet.ITEMS, Rarity.COMMON, ItemID.BIG_BONES, -1),
	YEW_LOGS("Yew Logs", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.YEW_LOGS, -1),
	MAGIC_LOGS("Magic Logs", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.MAGIC_LOGS, -1),
	REDWOOD_LOGS("Redwood Logs", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.REDWOOD_LOGS, -1),
	GOLD_ORE("Gold Ore", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.GOLD_ORE, -1),
	MITHRIL_ORE("Mithril Ore", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.MITHRIL_ORE, -1),
	ADAMANTITE_ORE("Adamantite Ore", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.ADAMANTITE_ORE, -1),
	RAW_LOBSTER("Raw Lobster", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.RAW_LOBSTER, -1),
	RAW_SWORDFISH("Raw Swordfish", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.RAW_SWORDFISH, -1),
	RANARR_WEED("Ranarr Weed", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.RANARR_WEED, -1),
	DRAGON_BONES("Dragon Bones", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.DRAGON_BONES, -1),
	IRON_SCIMITAR("Iron Scimitar", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.IRON_SCIMITAR, -1),
	STEEL_SCIMITAR("Steel Scimitar", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.STEEL_SCIMITAR, -1),
	MITHRIL_SCIMITAR("Mithril Scimitar", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.MITHRIL_SCIMITAR, -1),
	ADAMANT_SCIMITAR("Adamant Scimitar", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.ADAMANT_SCIMITAR, -1),
	RUNITE_ORE("Runite Ore", CardSet.ITEMS, Rarity.RARE, ItemID.RUNITE_ORE, -1),
	RAW_SHARK("Raw Shark", CardSet.ITEMS, Rarity.RARE, ItemID.RAW_SHARK, -1),
	SHARK("Shark", CardSet.ITEMS, Rarity.RARE, ItemID.SHARK, -1),
	RAW_ANGLERFISH("Raw Anglerfish", CardSet.ITEMS, Rarity.RARE, ItemID.RAW_ANGLERFISH, -1),
	SNAPDRAGON("Snapdragon", CardSet.ITEMS, Rarity.RARE, ItemID.SNAPDRAGON, -1),
	TORSTOL("Torstol", CardSet.ITEMS, Rarity.RARE, ItemID.TORSTOL, -1),
	AMETHYST("Amethyst", CardSet.ITEMS, Rarity.RARE, ItemID.AMETHYST, -1),
	RUNE_SCIMITAR("Rune Scimitar", CardSet.ITEMS, Rarity.RARE, ItemID.RUNE_SCIMITAR, -1),
	DRAGON_SCIMITAR("Dragon Scimitar", CardSet.ITEMS, Rarity.RARE, ItemID.DRAGON_SCIMITAR, -1),
	GRANITE_MAUL("Granite Maul", CardSet.ITEMS, Rarity.RARE, ItemID.GRANITE_MAUL, -1),
	DRAGON_PICKAXE("Dragon Pickaxe", CardSet.ITEMS, Rarity.RARE, ItemID.DRAGON_PICKAXE, -1),
	OCCULT_NECKLACE("Occult Necklace", CardSet.ITEMS, Rarity.RARE, ItemID.OCCULT_NECKLACE, -1),
	CRYSTAL_BOW("Crystal Bow", CardSet.ITEMS, Rarity.RARE, ItemID.CRYSTAL_BOW, -1),
	ABYSSAL_WHIP("Abyssal Whip", CardSet.ITEMS, Rarity.EPIC, ItemID.ABYSSAL_WHIP, -1),
	DRAGON_CLAWS("Dragon Claws", CardSet.ITEMS, Rarity.EPIC, ItemID.DRAGON_CLAWS, -1),
	TOXIC_BLOWPIPE("Toxic Blowpipe", CardSet.ITEMS, Rarity.EPIC, ItemID.TOXIC_BLOWPIPE, -1),
	ARMADYL_CHESTPLATE("Armadyl Chestplate", CardSet.ITEMS, Rarity.EPIC, ItemID.ARMADYL_CHESTPLATE, -1),
	BANDOS_CHESTPLATE("Bandos Chestplate", CardSet.ITEMS, Rarity.EPIC, ItemID.BANDOS_CHESTPLATE, -1),
	PRIMORDIAL_BOOTS("Primordial Boots", CardSet.ITEMS, Rarity.EPIC, ItemID.PRIMORDIAL_BOOTS, -1),
	ETERNAL_BOOTS("Eternal Boots", CardSet.ITEMS, Rarity.EPIC, ItemID.ETERNAL_BOOTS, -1),
	PEGASIAN_BOOTS("Pegasian Boots", CardSet.ITEMS, Rarity.EPIC, ItemID.PEGASIAN_BOOTS, -1),
	SANGUINESTI_STAFF("Sanguinesti Staff", CardSet.ITEMS, Rarity.EPIC, ItemID.SANGUINESTI_STAFF, -1),
	KODAI_WAND("Kodai Wand", CardSet.ITEMS, Rarity.EPIC, ItemID.KODAI_WAND, -1),
	ANCESTRAL_HAT("Ancestral Hat", CardSet.ITEMS, Rarity.EPIC, ItemID.ANCESTRAL_HAT, -1),
	INFERNAL_CAPE("Infernal Cape", CardSet.ITEMS, Rarity.EPIC, ItemID.INFERNAL_CAPE, -1),
	ELDER_MAUL("Elder Maul", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.ELDER_MAUL, -1),
	GHRAZI_RAPIER("Ghrazi Rapier", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.GHRAZI_RAPIER, -1),
	INQUISITOR_S_MACE("Inquisitor's Mace", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.INQUISITORS_MACE, -1),
	VOIDWAKER("Voidwaker", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.VOIDWAKER, -1),
	AIR_RUNE("Air Rune", CardSet.ITEMS, Rarity.COMMON, ItemID.AIRRUNE, -1),
	WATER_RUNE("Water Rune", CardSet.ITEMS, Rarity.COMMON, ItemID.WATERRUNE, -1),
	EARTH_RUNE("Earth Rune", CardSet.ITEMS, Rarity.COMMON, ItemID.EARTHRUNE, -1),
	FIRE_RUNE("Fire Rune", CardSet.ITEMS, Rarity.COMMON, ItemID.FIRERUNE, -1),
	MIND_RUNE("Mind Rune", CardSet.ITEMS, Rarity.COMMON, ItemID.MINDRUNE, -1),
	BODY_RUNE("Body Rune", CardSet.ITEMS, Rarity.COMMON, ItemID.BODYRUNE, -1),
	CHAOS_RUNE("Chaos Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.CHAOSRUNE, -1),
	COSMIC_RUNE("Cosmic Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.COSMICRUNE, -1),
	NATURE_RUNE("Nature Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.NATURERUNE, -1),
	LAW_RUNE("Law Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.LAWRUNE, -1),
	DEATH_RUNE("Death Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.DEATHRUNE, -1),
	MIST_RUNE("Mist Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.MISTRUNE, -1),
	DUST_RUNE("Dust Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.DUSTRUNE, -1),
	MUD_RUNE("Mud Rune", CardSet.ITEMS, Rarity.RARE, ItemID.MUDRUNE, -1),
	SMOKE_RUNE("Smoke Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.SMOKERUNE, -1),
	STEAM_RUNE("Steam Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.STEAMRUNE, -1),
	LAVA_RUNE("Lava Rune", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.LAVARUNE, -1),
	BLOOD_RUNE("Blood Rune", CardSet.ITEMS, Rarity.RARE, ItemID.BLOODRUNE, -1),
	SOUL_RUNE("Soul Rune", CardSet.ITEMS, Rarity.RARE, ItemID.SOULRUNE, -1),
	ASTRAL_RUNE("Astral Rune", CardSet.ITEMS, Rarity.RARE, ItemID.ASTRALRUNE, -1),
	WRATH_RUNE("Wrath Rune", CardSet.ITEMS, Rarity.RARE, ItemID.WRATHRUNE, -1),
	SUNFIRE_RUNE("Sunfire Rune", CardSet.ITEMS, Rarity.EPIC, ItemID.SUNFIRERUNE, -1),
	AETHER_RUNE("Aether Rune", CardSet.ITEMS, Rarity.EPIC, ItemID.AETHERRUNE, -1),
	MARRENTILL("Marrentill", CardSet.ITEMS, Rarity.COMMON, ItemID.MARENTILL, -1),
	TARROMIN("Tarromin", CardSet.ITEMS, Rarity.COMMON, ItemID.TARROMIN, -1),
	HARRALANDER("Harralander", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.HARRALANDER, -1),
	TOADFLAX("Toadflax", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.TOADFLAX, -1),
	IRIT_LEAF("Irit Leaf", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.IRIT_LEAF, -1),
	AVANTOE("Avantoe", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.AVANTOE, -1),
	KWUARM("Kwuarm", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.KWUARM, -1),
	HUASCA("Huasca", CardSet.ITEMS, Rarity.RARE, ItemID.HUASCA, -1),
	CADANTINE("Cadantine", CardSet.ITEMS, Rarity.RARE, ItemID.CADANTINE, -1),
	LANTADYME("Lantadyme", CardSet.ITEMS, Rarity.RARE, ItemID.LANTADYME, -1),
	DWARF_WEED("Dwarf Weed", CardSet.ITEMS, Rarity.RARE, ItemID.DWARF_WEED, -1),
	RAW_SHRIMPS("Raw Shrimps", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_SHRIMP, -1),
	RAW_ANCHOVIES("Raw Anchovies", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_ANCHOVIES, -1),
	RAW_SARDINE("Raw Sardine", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_SARDINE, -1),
	RAW_HERRING("Raw Herring", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_HERRING, -1),
	RAW_MACKEREL("Raw Mackerel", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_MACKEREL, -1),
	RAW_COD("Raw Cod", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_COD, -1),
	RAW_PIKE("Raw Pike", CardSet.ITEMS, Rarity.COMMON, ItemID.RAW_PIKE, -1),
	RAW_TUNA("Raw Tuna", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.RAW_TUNA, -1),
	RAW_BASS("Raw Bass", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.RAW_BASS, -1),
	RAW_MONKFISH("Raw Monkfish", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.RAW_MONKFISH, -1),
	RAW_KARAMBWAN("Raw Karambwan", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.TBWT_RAW_KARAMBWAN, -1),
	RAW_SEA_TURTLE("Raw Sea Turtle", CardSet.ITEMS, Rarity.RARE, ItemID.RAW_SEATURTLE, -1),
	RAW_MANTA_RAY("Raw Manta Ray", CardSet.ITEMS, Rarity.RARE, ItemID.RAW_MANTARAY, -1),
	RAW_DARK_CRAB("Raw Dark Crab", CardSet.ITEMS, Rarity.RARE, ItemID.RAW_DARK_CRAB, -1),
	UNCUT_ONYX("Uncut Onyx", CardSet.ITEMS, Rarity.EPIC, ItemID.UNCUT_ONYX, -1),
	ZULRAH_S_SCALES("Zulrah's Scales", CardSet.ITEMS, Rarity.COMMON, ItemID.SNAKEBOSS_SCALE, -1),
	DEXTEROUS_PRAYER_SCROLL("Dexterous Prayer Scroll", CardSet.ITEMS, Rarity.RARE, ItemID.RAIDS_PRAYERSCROLL, -1),
	ARCANE_PRAYER_SCROLL("Arcane Prayer Scroll", CardSet.ITEMS, Rarity.RARE, ItemID.RAIDS_PRAYERSCROLL_AUGURY, -1),
	TWISTED_BUCKLER("Twisted Buckler", CardSet.ITEMS, Rarity.EPIC, ItemID.TWISTED_BUCKLER, -1),
	DRAGON_HUNTER_CROSSBOW("Dragon Hunter Crossbow", CardSet.ITEMS, Rarity.EPIC, ItemID.DRAGONHUNTER_XBOW, -1),
	DINH_S_BULWARK("Dinh's Bulwark", CardSet.ITEMS, Rarity.EPIC, ItemID.DINHS_BULWARK, -1),
	ANCESTRAL_ROBE_TOP("Ancestral Robe Top", CardSet.ITEMS, Rarity.EPIC, ItemID.ANCESTRAL_ROBE_TOP, -1),
	TWISTED_BOW("Twisted Bow", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.TWISTED_BOW, -1),
	JUSTICIAR_FACEGUARD("Justiciar Faceguard", CardSet.ITEMS, Rarity.EPIC, ItemID.JUSTICIAR_FACEGUARD, -1),
	JUSTICIAR_CHESTGUARD("Justiciar Chestguard", CardSet.ITEMS, Rarity.EPIC, ItemID.JUSTICIAR_CHESTGUARD, -1),
	AVERNIC_DEFENDER("Avernic Defender", CardSet.ITEMS, Rarity.EPIC, ItemID.INFERNAL_DEFENDER, -1),
	SCYTHE_OF_VITUR("Scythe of Vitur", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.SCYTHE_OF_VITUR, -1),
	OSMUMTEN_S_FANG("Osmumten's Fang", CardSet.ITEMS, Rarity.EPIC, ItemID.OSMUMTENS_FANG, -1),
	LIGHTBEARER("Lightbearer", CardSet.ITEMS, Rarity.EPIC, ItemID.LIGHTBEARER, -1),
	ELIDINIS_WARD("Elidinis' Ward", CardSet.ITEMS, Rarity.EPIC, ItemID.ELIDINIS_WARD, -1),
	MASORI_MASK("Masori Mask", CardSet.ITEMS, Rarity.EPIC, ItemID.MASORI_MASK, -1),
	MASORI_BODY("Masori Body", CardSet.ITEMS, Rarity.EPIC, ItemID.MASORI_BODY, -1),
	TUMEKEN_S_SHADOW("Tumeken's Shadow", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.TUMEKENS_SHADOW, -1),
	ARMADYL_CROSSBOW("Armadyl Crossbow", CardSet.ITEMS, Rarity.EPIC, ItemID.ACB, -1),
	SARADOMIN_SWORD("Saradomin Sword", CardSet.ITEMS, Rarity.RARE, ItemID.SARADOMIN_SWORD, -1),
	ZAMORAKIAN_SPEAR("Zamorakian Spear", CardSet.ITEMS, Rarity.RARE, ItemID.ZAMORAK_SPEAR, -1),
	STAFF_OF_THE_DEAD("Staff of the Dead", CardSet.ITEMS, Rarity.EPIC, ItemID.SOTD, -1),
	BANDOS_TASSETS("Bandos Tassets", CardSet.ITEMS, Rarity.EPIC, ItemID.BANDOS_SKIRT, -1),
	ARMADYL_HELMET("Armadyl Helmet", CardSet.ITEMS, Rarity.EPIC, ItemID.ARMADYL_HELMET, -1),
	TORVA_FULL_HELM("Torva Full Helm", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.TORVA_HELM, -1),
	TORVA_PLATEBODY("Torva Platebody", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.TORVA_CHEST, -1),
	ZARYTE_VAMBRACES("Zaryte Vambraces", CardSet.ITEMS, Rarity.EPIC, ItemID.ZARYTE_VAMBRACES, -1),
	VIRTUS_MASK("Virtus Mask", CardSet.ITEMS, Rarity.EPIC, ItemID.VIRTUS_MASK, -1),
	VIRTUS_ROBE_TOP("Virtus Robe Top", CardSet.ITEMS, Rarity.EPIC, ItemID.VIRTUS_TOP, -1),
	NIGHTMARE_STAFF("Nightmare Staff", CardSet.ITEMS, Rarity.EPIC, ItemID.NIGHTMARE_STAFF, -1),
	HARMONISED_ORB("Harmonised Orb", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.HARMONISED_ORB, -1),
	VOLATILE_ORB("Volatile Orb", CardSet.ITEMS, Rarity.EPIC, ItemID.VOLATILE_ORB, -1),
	ELDRITCH_ORB("Eldritch Orb", CardSet.ITEMS, Rarity.EPIC, ItemID.ELDRITCH_ORB, -1),
	ULTOR_VESTIGE("Ultor Vestige", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.ULTOR_VESTIGE, -1),
	MAGUS_VESTIGE("Magus Vestige", CardSet.ITEMS, Rarity.EPIC, ItemID.MAGUS_VESTIGE, -1),
	VENATOR_VESTIGE("Venator Vestige", CardSet.ITEMS, Rarity.EPIC, ItemID.VENATOR_VESTIGE, -1),
	BELLATOR_VESTIGE("Bellator Vestige", CardSet.ITEMS, Rarity.EPIC, ItemID.BELLATOR_VESTIGE, -1),
	AWAKENER_S_ORB("Awakener's Orb", CardSet.ITEMS, Rarity.EPIC, ItemID.DT2_AWAKENERS_ORB, -1),
	NOXIOUS_HALBERD("Noxious Halberd", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.NOXIOUS_HALBERD, -1),
	ARAXYTE_FANG("Araxyte Fang", CardSet.ITEMS, Rarity.EPIC, ItemID.ARAXYTE_FANG, -1),
	AMULET_OF_RANCOUR("Amulet of Rancour", CardSet.ITEMS, Rarity.EPIC, ItemID.AMULET_OF_RANCOUR, -1),
	ABYSSAL_DAGGER("Abyssal Dagger", CardSet.ITEMS, Rarity.RARE, ItemID.ABYSSAL_DAGGER, -1),
	ABYSSAL_BLUDGEON("Abyssal Bludgeon", CardSet.ITEMS, Rarity.EPIC, ItemID.ABYSSAL_BLUDGEON, -1),
	KRAKEN_TENTACLE("Kraken Tentacle", CardSet.ITEMS, Rarity.RARE, ItemID.KRAKEN_TENTACLE, -1),
	HYDRA_S_CLAW("Hydra's Claw", CardSet.ITEMS, Rarity.EPIC, ItemID.HYDRA_CLAW, -1),
	HYDRA_TAIL("Hydra Tail", CardSet.ITEMS, Rarity.RARE, ItemID.HYDRA_TAIL, -1),
	HYDRA_LEATHER("Hydra Leather", CardSet.ITEMS, Rarity.RARE, ItemID.HYDRA_LEATHER, -1),
	SARACHNIS_CUDGEL("Sarachnis Cudgel", CardSet.ITEMS, Rarity.RARE, ItemID.SARACHNIS_CUDGEL, -1),
	PRIMORDIAL_CRYSTAL("Primordial Crystal", CardSet.ITEMS, Rarity.EPIC, ItemID.PRIMORDIAL_CRYSTAL, -1),
	PEGASIAN_CRYSTAL("Pegasian Crystal", CardSet.ITEMS, Rarity.EPIC, ItemID.PEGASIAN_CRYSTAL, -1),
	ETERNAL_CRYSTAL("Eternal Crystal", CardSet.ITEMS, Rarity.EPIC, ItemID.ETERNAL_CRYSTAL, -1),
	SMOULDERING_STONE("Smouldering Stone", CardSet.ITEMS, Rarity.RARE, ItemID.SMOULDERING_STONE, -1),
	GRANITE_HAMMER("Granite Hammer", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.GRANITE_HAMMER, -1),
	ELYSIAN_SIGIL("Elysian Sigil", CardSet.ITEMS, Rarity.LEGENDARY, ItemID.ELYSIAN_SIGIL, -1),
	SERPENTINE_VISAGE("Serpentine Visage", CardSet.ITEMS, Rarity.RARE, ItemID.SERPENTINE_VISAGE, -1),
	DRACONIC_VISAGE("Draconic Visage", CardSet.ITEMS, Rarity.EPIC, ItemID.DRAGONFIRE_VISAGE, -1),
	TANZANITE_FANG("Tanzanite Fang", CardSet.ITEMS, Rarity.RARE, ItemID.BLOWPIPE_FANG, -1),
	MAGIC_FANG("Magic Fang", CardSet.ITEMS, Rarity.RARE, ItemID.MAGIC_FANG, -1),
	DRAGON_HARPOON("Dragon Harpoon", CardSet.ITEMS, Rarity.RARE, ItemID.DRAGON_HARPOON, -1),
	TOME_OF_FIRE("Tome of Fire", CardSet.ITEMS, Rarity.RARE, ItemID.TOME_OF_FIRE, -1),
	TOME_OF_WATER("Tome of Water", CardSet.ITEMS, Rarity.RARE, ItemID.TOME_OF_WATER, -1),
	RING_OF_THE_GODS("Ring of the Gods", CardSet.ITEMS, Rarity.RARE, ItemID.ROTG, -1),
	TREASONOUS_RING("Treasonous Ring", CardSet.ITEMS, Rarity.RARE, ItemID.SHARP_RING, -1),
	TYRANNICAL_RING("Tyrannical Ring", CardSet.ITEMS, Rarity.RARE, ItemID.HEAVY_RING, -1),
	SMOKE_BATTLESTAFF("Smoke Battlestaff", CardSet.ITEMS, Rarity.UNCOMMON, ItemID.SMOKE_BATTLESTAFF, -1),
	BARBARIAN_ASSAULT("Barbarian Assault", CardSet.MINIGAMES, Rarity.COMMON, ItemID.BARBASSAULT_PENANCE_FIGHTER_TORSO, -1),
	PEST_CONTROL("Pest Control", CardSet.MINIGAMES, Rarity.COMMON, ItemID.PEST_VOID_KNIGHT_TOP, -1),
	CASTLE_WARS("Castle Wars", CardSet.MINIGAMES, Rarity.COMMON, ItemID.CASTLEWARS_CLOAK_SARADOMIN, -1),
	BLAST_FURNACE("Blast Furnace", CardSet.MINIGAMES, Rarity.COMMON, ItemID.GAUNTLETS_OF_GOLDSMITHING, -1),
	TITHE_FARM("Tithe Farm", CardSet.MINIGAMES, Rarity.COMMON, ItemID.TITHE_REWARD_TORSO_MALE, -1),
	PYRAMID_PLUNDER("Pyramid Plunder", CardSet.MINIGAMES, Rarity.COMMON, ItemID.PHARAOHS_SCEPTRE, -1),
	BRIMHAVEN_AGILITY_ARENA("Brimhaven Agility Arena", CardSet.MINIGAMES, Rarity.COMMON, ItemID.AGILITYARENA_TICKET, -1),
	ROGUES_DEN("Rogues' Den", CardSet.MINIGAMES, Rarity.UNCOMMON, ItemID.ROGUESDEN_BODY, -1),
	TROUBLE_BREWING("Trouble Brewing", CardSet.MINIGAMES, Rarity.UNCOMMON, ItemID.ASGARNIAN_ALE, -1),
	MAGE_TRAINING_ARENA("Mage Training Arena", CardSet.MINIGAMES, Rarity.UNCOMMON, ItemID.MAGICTRAINING_INFINITYHAT, -1),
	GNOME_RESTAURANT("Gnome Restaurant", CardSet.MINIGAMES, Rarity.UNCOMMON, ItemID.BALL_GNOMEBALL_GAME, -1),
	VOLCANIC_MINE("Volcanic Mine", CardSet.MINIGAMES, Rarity.UNCOMMON, ItemID.FOSSIL_VOLCANIC_ASH, -1),
	GUARDIANS_OF_THE_RIFT("Guardians of the Rift", CardSet.MINIGAMES, Rarity.UNCOMMON, ItemID.ABYSSAL_LANTERN, -1),
	LAST_MAN_STANDING("Last Man Standing", CardSet.MINIGAMES, Rarity.RARE, ItemID.BLIGHTED_KARAMBWAN, -1),
	SOUL_WARS("Soul Wars", CardSet.MINIGAMES, Rarity.RARE, ItemID.SOUL_CAPE_RED, -1),
	NIGHTMARE_ZONE("Nightmare Zone", CardSet.MINIGAMES, Rarity.RARE, ItemID.IMBUED_HEART, -1),
	FIGHT_CAVES("Fight Caves", CardSet.MINIGAMES, Rarity.EPIC, ItemID.TZHAAR_CAPE_FIRE, -1),
	INFERNO("Inferno", CardSet.MINIGAMES, Rarity.LEGENDARY, ItemID.INFERNAL_CAPE, -1),
	CRAWLING_HAND("Crawling Hand", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_CRAWLINGHAND, -1),
	CAVE_BUG("Cave Bug", CardSet.SLAYER, Rarity.COMMON, -1, SpriteID.Staticons2.SLAYER),
	CAVE_CRAWLER("Cave Crawler", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_CAVECRAWLER, -1),
	BANSHEE("Banshee", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_BANSHEE, -1),
	CAVE_SLIME("Cave Slime", CardSet.SLAYER, Rarity.COMMON, ItemID.BOOTS_OF_STONE, -1),
	ROCKSLUG("Rockslug", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_ROCKSLUG, -1),
	DESERT_LIZARD("Desert Lizard", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_LIZARD, -1),
	COCKATRICE("Cockatrice", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_COCKATRICE, -1),
	PYREFIEND("Pyrefiend", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_PYRFIEND, -1),
	MOGRE("Mogre", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_MOGRE, -1),
	HARPIE_BUG_SWARM("Harpie Bug Swarm", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_SWARM, -1),
	WALL_BEAST("Wall Beast", CardSet.SLAYER, Rarity.COMMON, -1, SpriteID.Staticons2.SLAYER),
	KILLERWATT("Killerwatt", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_KILLERWATT, -1),
	VYRE("Vyre", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_VAMPYRE, -1),
	MOLANISK("Molanisk", CardSet.SLAYER, Rarity.COMMON, ItemID.SLAYERGUIDE_MOLANISK, -1),
	BASILISK("Basilisk", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_BASILISK, -1),
	SEA_SNAKE("Sea Snake", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SEAWEED, -1),
	TERROR_DOG("Terror Dog", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_TERRORDOG, -1),
	FEVER_SPIDER("Fever Spider", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_FEVER_SPIDER, -1),
	SULPHUR_LIZARD("Sulphur Lizard", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_SULPHURLIZARDS, -1),
	INFERNAL_MAGE("Infernal Mage", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_INFERNALMAGE, -1),
	BRINE_RAT("Brine Rat", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.OLAF2_BRINE_SABRE, -1),
	LESSER_NAGUA("Lesser Nagua", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_LESSER_NAGUA, -1),
	BLOODVELD("Bloodveld", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_BLOODVELD, -1),
	GRYPHON("Gryphon", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_GRYPHON, -1),
	JELLY("Jelly", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_JELLY, -1),
	JUVENILE_CUSTODIAN_STALKER("Juvenile Custodian Stalker", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_CUSTODIAN_STALKER_JUVENILE, -1),
	TUROTH("Turoth", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_TUROTH, -1),
	WARPED_CREATURE("Warped Creature", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.WARPED_SCEPTRE, -1),
	MUTATED_ZYGOMITE("Mutated Zygomite", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYER_FUNGICIDE, -1),
	CAVE_HORROR("Cave Horror", CardSet.SLAYER, Rarity.UNCOMMON, ItemID.SLAYERGUIDE_HARMLESS_CAVE_HORROR, -1),
	ABERRANT_SPECTRE("Aberrant Spectre", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_ABERRANTSPECTER, -1),
	BASILISK_KNIGHT("Basilisk Knight", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_BASILISK_KNIGHT, -1),
	WYRM("Wyrm", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_WYRM, -1),
	SPIRITUAL_RANGER("Spiritual Ranger", CardSet.SLAYER, Rarity.RARE, ItemID.RUNE_SPEAR, -1),
	DUST_DEVIL("Dust Devil", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_DUSTDEVIL, -1),
	FOSSIL_ISLAND_WYVERN("Fossil Island Wyvern", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_FOSSILWYVERN, -1),
	MATURE_CUSTODIAN_STALKER("Mature Custodian Stalker", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_CUSTODIAN_STALKER_MATURE, -1),
	SPIRITUAL_WARRIOR("Spiritual Warrior", CardSet.SLAYER, Rarity.RARE, ItemID.DRAGON_BOOTS, -1),
	KURASK("Kurask", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_KURASK, -1),
	SKELETAL_WYVERN("Skeletal Wyvern", CardSet.SLAYER, Rarity.RARE, ItemID.SLAYERGUIDE_SKELETALWYVERN, -1),
	VENATOR("Venator", CardSet.SLAYER, Rarity.RARE, ItemID.VENATOR_BOW, -1),
	GARGOYLE("Gargoyle", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_GARGOYLE, -1),
	ELDER_CUSTODIAN_STALKER("Elder Custodian Stalker", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_CUSTODIAN_STALKER_ELDER, -1),
	BRUTAL_BLACK_DRAGON("Brutal Black Dragon", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_BRUTAL_BLACK, -1),
	AQUANITE("Aquanite", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_AQUANITE, -1),
	NECHRYAEL("Nechryael", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_NECHRYAEL, -1),
	ANCIENT_WYVERN("Ancient Wyvern", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_FOSSILANCIENTWYVERN, -1),
	SPIRITUAL_MAGE("Spiritual Mage", CardSet.SLAYER, Rarity.EPIC, ItemID.BLESSED_SPIRIT_SHIELD, -1),
	DRAKE("Drake", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_DRAKE, -1),
	ABYSSAL_DEMON("Abyssal Demon", CardSet.SLAYER, Rarity.EPIC, ItemID.SLAYERGUIDE_ABYSSALDEMON, -1),
	CAVE_KRAKEN("Cave Kraken", CardSet.SLAYER, Rarity.EPIC, ItemID.KRAKEN_TENTACLE, -1),
	DARK_BEAST("Dark Beast", CardSet.SLAYER, Rarity.LEGENDARY, ItemID.SLAYERGUIDE_DARK_BEAST, -1),
	ARAXYTE("Araxyte", CardSet.SLAYER, Rarity.LEGENDARY, ItemID.ARAXYTE_VENOM_SACK, -1),
	SMOKE_DEVIL("Smoke Devil", CardSet.SLAYER, Rarity.LEGENDARY, ItemID.SMOKE_BATTLESTAFF, -1),
	HYDRA("Hydra", CardSet.SLAYER, Rarity.LEGENDARY, ItemID.SLAYERGUIDE_HYDRA, -1),
	ARDOUGNE_EASY("Ardougne Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.ARDY_CAPE_EASY, -1),
	ARDOUGNE_MEDIUM("Ardougne Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.ARDY_CAPE_MEDIUM, -1),
	ARDOUGNE_HARD("Ardougne Hard", CardSet.DIARIES, Rarity.RARE, ItemID.ARDY_CAPE_HARD, -1),
	ARDOUGNE_ELITE("Ardougne Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.ARDY_CAPE_ELITE, -1),
	DESERT_EASY("Desert Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.DESERT_AMULET_EASY, -1),
	DESERT_MEDIUM("Desert Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.DESERT_AMULET_MEDIUM, -1),
	DESERT_HARD("Desert Hard", CardSet.DIARIES, Rarity.RARE, ItemID.DESERT_AMULET_HARD, -1),
	DESERT_ELITE("Desert Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.DESERT_AMULET_ELITE, -1),
	FALADOR_EASY("Falador Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.FALADOR_SHIELD_EASY, -1),
	FALADOR_MEDIUM("Falador Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.FALADOR_SHIELD_MEDIUM, -1),
	FALADOR_HARD("Falador Hard", CardSet.DIARIES, Rarity.RARE, ItemID.FALADOR_SHIELD_HARD, -1),
	FALADOR_ELITE("Falador Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.FALADOR_SHIELD_ELITE, -1),
	FREMENNIK_EASY("Fremennik Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.FREMENNIK_BOOTS_EASY, -1),
	FREMENNIK_MEDIUM("Fremennik Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.FREMENNIK_BOOTS_MEDIUM, -1),
	FREMENNIK_HARD("Fremennik Hard", CardSet.DIARIES, Rarity.RARE, ItemID.FREMENNIK_BOOTS_HARD, -1),
	FREMENNIK_ELITE("Fremennik Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.FREMENNIK_BOOTS_ELITE, -1),
	KANDARIN_EASY("Kandarin Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.SEERS_HEADBAND_EASY, -1),
	KANDARIN_MEDIUM("Kandarin Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.SEERS_HEADBAND_MEDIUM, -1),
	KANDARIN_HARD("Kandarin Hard", CardSet.DIARIES, Rarity.RARE, ItemID.SEERS_HEADBAND_HARD, -1),
	KANDARIN_ELITE("Kandarin Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.SEERS_HEADBAND_ELITE, -1),
	KARAMJA_EASY("Karamja Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.ATJUN_GLOVES_EASY, -1),
	KARAMJA_MEDIUM("Karamja Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.ATJUN_GLOVES_MED, -1),
	KARAMJA_HARD("Karamja Hard", CardSet.DIARIES, Rarity.RARE, ItemID.ATJUN_GLOVES_HARD, -1),
	KARAMJA_ELITE("Karamja Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.ATJUN_GLOVES_ELITE, -1),
	KOUREND_KEBOS_EASY("Kourend & Kebos Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.ZEAH_BLESSING_EASY, -1),
	KOUREND_KEBOS_MEDIUM("Kourend & Kebos Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.ZEAH_BLESSING_MEDIUM, -1),
	KOUREND_KEBOS_HARD("Kourend & Kebos Hard", CardSet.DIARIES, Rarity.RARE, ItemID.ZEAH_BLESSING_HARD, -1),
	KOUREND_KEBOS_ELITE("Kourend & Kebos Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.ZEAH_BLESSING_ELITE, -1),
	LUMBRIDGE_DRAYNOR_EASY("Lumbridge & Draynor Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.LUMBRIDGE_RING_EASY, -1),
	LUMBRIDGE_DRAYNOR_MEDIUM("Lumbridge & Draynor Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.LUMBRIDGE_RING_MEDIUM, -1),
	LUMBRIDGE_DRAYNOR_HARD("Lumbridge & Draynor Hard", CardSet.DIARIES, Rarity.RARE, ItemID.LUMBRIDGE_RING_HARD, -1),
	LUMBRIDGE_DRAYNOR_ELITE("Lumbridge & Draynor Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.LUMBRIDGE_RING_ELITE, -1),
	MORYTANIA_EASY("Morytania Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.MORYTANIA_LEGS_EASY, -1),
	MORYTANIA_MEDIUM("Morytania Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.MORYTANIA_LEGS_MEDIUM, -1),
	MORYTANIA_HARD("Morytania Hard", CardSet.DIARIES, Rarity.RARE, ItemID.MORYTANIA_LEGS_HARD, -1),
	MORYTANIA_ELITE("Morytania Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.MORYTANIA_LEGS_ELITE, -1),
	VARROCK_EASY("Varrock Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.VARROCK_ARMOUR_EASY, -1),
	VARROCK_MEDIUM("Varrock Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.VARROCK_ARMOUR_MEDIUM, -1),
	VARROCK_HARD("Varrock Hard", CardSet.DIARIES, Rarity.RARE, ItemID.VARROCK_ARMOUR_HARD, -1),
	VARROCK_ELITE("Varrock Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.VARROCK_ARMOUR_ELITE, -1),
	WESTERN_PROVINCES_EASY("Western Provinces Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.WESTERN_BANNER_EASY, -1),
	WESTERN_PROVINCES_MEDIUM("Western Provinces Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.WESTERN_BANNER_MEDIUM, -1),
	WESTERN_PROVINCES_HARD("Western Provinces Hard", CardSet.DIARIES, Rarity.RARE, ItemID.WESTERN_BANNER_HARD, -1),
	WESTERN_PROVINCES_ELITE("Western Provinces Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.WESTERN_BANNER_ELITE, -1),
	WILDERNESS_EASY("Wilderness Easy", CardSet.DIARIES, Rarity.COMMON, ItemID.WILDERNESS_SWORD_EASY, -1),
	WILDERNESS_MEDIUM("Wilderness Medium", CardSet.DIARIES, Rarity.UNCOMMON, ItemID.WILDERNESS_SWORD_MEDIUM, -1),
	WILDERNESS_HARD("Wilderness Hard", CardSet.DIARIES, Rarity.RARE, ItemID.WILDERNESS_SWORD_HARD, -1),
	WILDERNESS_ELITE("Wilderness Elite", CardSet.DIARIES, Rarity.EPIC, ItemID.WILDERNESS_SWORD_ELITE, -1),
	ACHIEVEMENT_DIARY_CAPE("Achievement Diary Cape", CardSet.DIARIES, Rarity.LEGENDARY, ItemID.SKILLCAPE_AD_TRIMMED, -1);


	private final String id;
	private final String displayName;
	private final CardSet set;
	private final Rarity rarity;
	private final int itemId;
	private final int spriteId;
	private final Card card;

	Cards(String displayName, CardSet set, Rarity rarity, int itemId, int spriteId)
	{
		this.displayName = displayName;
		this.set = set;
		this.rarity = rarity;
		this.itemId = itemId;
		this.spriteId = spriteId;
		this.id = set.name().toLowerCase(Locale.ROOT) + "-"
			+ name().toLowerCase(Locale.ROOT).replace('_', '-');
		this.card = new Card(id, displayName, set, rarity, itemId, spriteId);
	}
}
