/*
 * Copyright (c) 2026, Zoinkwiz <https://github.com/Zoinkwiz>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The quest difficulty table below is derived from the quest declarations in Quest
 * Helper (https://github.com/Zoinkwiz/quest-helper), Copyright (c) 2020, Zoinkwiz and
 * the Quest Helper contributors, distributed under these same BSD 2-Clause terms.
 */
package com.dopaminesimulator.cards;

import java.util.HashMap;
import java.util.Map;
import net.runelite.api.Quest;

public final class QuestDifficulty
{
	public enum Tier
	{
		NOVICE(Rarity.COMMON),
		MINIQUEST(Rarity.UNCOMMON),
		INTERMEDIATE(Rarity.UNCOMMON),
		EXPERIENCED(Rarity.RARE),
		MASTER(Rarity.EPIC),
		GRANDMASTER(Rarity.LEGENDARY);
		private final Rarity rarity;
		Tier(Rarity rarity)
		{
			this.rarity = rarity;
		}
		public Rarity getRarity()
		{
			return rarity;
		}
	}
	private static final Map<String, Tier> TIERS = new HashMap<>();

	private QuestDifficulty()
	{
	}
	private static void put(String questConstant, Tier tier)
	{
		TIERS.put(questConstant, tier);
	}
	static
	{
		put("ALFRED_GRIMHANDS_BARCRAWL", Tier.MINIQUEST);
		put("ANIMAL_MAGNETISM", Tier.INTERMEDIATE);
		put("ANOTHER_SLICE_OF_HAM", Tier.INTERMEDIATE);
		put("AT_FIRST_LIGHT", Tier.NOVICE);
		put("A_KINGDOM_DIVIDED", Tier.EXPERIENCED);
		put("A_NIGHT_AT_THE_THEATRE", Tier.MASTER);
		put("A_PORCINE_OF_INTEREST", Tier.NOVICE);
		put("A_SOULS_BANE", Tier.INTERMEDIATE);
		put("A_TAIL_OF_TWO_CATS", Tier.INTERMEDIATE);
		put("A_TASTE_OF_HOPE", Tier.EXPERIENCED);
		put("BARBARIAN_TRAINING", Tier.MINIQUEST);
		put("BEAR_YOUR_SOUL", Tier.MINIQUEST);
		put("BELOW_ICE_MOUNTAIN", Tier.NOVICE);
		put("BENEATH_CURSED_SANDS", Tier.MASTER);
		put("BETWEEN_A_ROCK", Tier.EXPERIENCED);
		put("BIG_CHOMPY_BIRD_HUNTING", Tier.INTERMEDIATE);
		put("BIOHAZARD", Tier.NOVICE);
		put("BLACK_KNIGHTS_FORTRESS", Tier.INTERMEDIATE);
		put("BONE_VOYAGE", Tier.INTERMEDIATE);
		put("CABIN_FEVER", Tier.EXPERIENCED);
		put("CHILDREN_OF_THE_SUN", Tier.NOVICE);
		put("CLIENT_OF_KOUREND", Tier.NOVICE);
		put("CLOCK_TOWER", Tier.NOVICE);
		put("COLD_WAR", Tier.INTERMEDIATE);
		put("CONTACT", Tier.EXPERIENCED);
		put("COOKS_ASSISTANT", Tier.NOVICE);
		put("CREATURE_OF_FENKENSTRAIN", Tier.INTERMEDIATE);
		put("CURRENT_AFFAIRS", Tier.NOVICE);
		put("CURSE_OF_THE_EMPTY_LORD", Tier.MINIQUEST);
		put("DADDYS_HOME", Tier.MINIQUEST);
		put("DARKNESS_OF_HALLOWVALE", Tier.EXPERIENCED);
		put("DEATH_ON_THE_ISLE", Tier.INTERMEDIATE);
		put("DEATH_PLATEAU", Tier.NOVICE);
		put("DEATH_TO_THE_DORGESHUUN", Tier.INTERMEDIATE);
		put("DEFENDER_OF_VARROCK", Tier.EXPERIENCED);
		put("DEMON_SLAYER", Tier.NOVICE);
		put("DESERT_TREASURE_I", Tier.MASTER);
		put("DESERT_TREASURE_II__THE_FALLEN_EMPIRE", Tier.GRANDMASTER);
		put("DEVIOUS_MINDS", Tier.EXPERIENCED);
		put("DORICS_QUEST", Tier.NOVICE);
		put("DRAGON_SLAYER_I", Tier.EXPERIENCED);
		put("DRAGON_SLAYER_II", Tier.GRANDMASTER);
		put("DREAM_MENTOR", Tier.MASTER);
		put("DRUIDIC_RITUAL", Tier.NOVICE);
		put("DWARF_CANNON", Tier.NOVICE);
		put("EADGARS_RUSE", Tier.INTERMEDIATE);
		put("EAGLES_PEAK", Tier.NOVICE);
		put("ELEMENTAL_WORKSHOP_I", Tier.NOVICE);
		put("ELEMENTAL_WORKSHOP_II", Tier.INTERMEDIATE);
		put("ENAKHRAS_LAMENT", Tier.EXPERIENCED);
		put("ENLIGHTENED_JOURNEY", Tier.INTERMEDIATE);
		put("ENTER_THE_ABYSS", Tier.MINIQUEST);
		put("ERNEST_THE_CHICKEN", Tier.NOVICE);
		put("ETHICALLY_ACQUIRED_ANTIQUITIES", Tier.NOVICE);
		put("FAIRYTALE_II__CURE_A_QUEEN", Tier.EXPERIENCED);
		put("FAIRYTALE_I__GROWING_PAINS", Tier.INTERMEDIATE);
		put("FALLEN_FROM_GRACE", Tier.EXPERIENCED);
		put("FAMILY_CREST", Tier.EXPERIENCED);
		put("FAMILY_PEST", Tier.MINIQUEST);
		put("FIGHT_ARENA", Tier.INTERMEDIATE);
		put("FISHING_CONTEST", Tier.NOVICE);
		put("FORGETTABLE_TALE", Tier.INTERMEDIATE);
		put("GARDEN_OF_TRANQUILLITY", Tier.INTERMEDIATE);
		put("GERTRUDES_CAT", Tier.NOVICE);
		put("GETTING_AHEAD", Tier.INTERMEDIATE);
		put("GHOSTS_AHOY", Tier.INTERMEDIATE);
		put("GOBLIN_DIPLOMACY", Tier.NOVICE);
		put("GRIM_TALES", Tier.MASTER);
		put("HAUNTED_MINE", Tier.EXPERIENCED);
		put("HAZEEL_CULT", Tier.NOVICE);
		put("HEROES_QUEST", Tier.EXPERIENCED);
		put("HIS_FAITHFUL_SERVANTS", Tier.MINIQUEST);
		put("HOLY_GRAIL", Tier.INTERMEDIATE);
		put("HOPESPEARS_WILL", Tier.MINIQUEST);
		put("HORROR_FROM_THE_DEEP", Tier.INTERMEDIATE);
		put("ICTHLARINS_LITTLE_HELPER", Tier.INTERMEDIATE);
		put("IMP_CATCHER", Tier.NOVICE);
		put("INTO_THE_TOMBS", Tier.INTERMEDIATE);
		put("IN_AID_OF_THE_MYREQUE", Tier.INTERMEDIATE);
		put("IN_SEARCH_OF_KNOWLEDGE", Tier.MINIQUEST);
		put("IN_SEARCH_OF_THE_MYREQUE", Tier.INTERMEDIATE);
		put("JUNGLE_POTION", Tier.NOVICE);
		put("KINGS_RANSOM", Tier.EXPERIENCED);
		put("LAIR_OF_TARN_RAZORLOR", Tier.MINIQUEST);
		put("LAND_OF_THE_GOBLINS", Tier.EXPERIENCED);
		put("LEARNING_THE_ROPES", Tier.NOVICE);
		put("LEGENDS_QUEST", Tier.MASTER);
		put("LOST_CITY", Tier.INTERMEDIATE);
		put("LUNAR_DIPLOMACY", Tier.EXPERIENCED);
		put("MAGE_ARENA_I", Tier.MINIQUEST);
		put("MAGE_ARENA_II", Tier.MINIQUEST);
		put("MAKING_FRIENDS_WITH_MY_ARM", Tier.MASTER);
		put("MAKING_HISTORY", Tier.INTERMEDIATE);
		put("MEAT_AND_GREET", Tier.EXPERIENCED);
		put("MERLINS_CRYSTAL", Tier.INTERMEDIATE);
		put("MISTHALIN_MYSTERY", Tier.NOVICE);
		put("MONKEY_MADNESS_I", Tier.MASTER);
		put("MONKEY_MADNESS_II", Tier.GRANDMASTER);
		put("MONKS_FRIEND", Tier.NOVICE);
		put("MOUNTAIN_DAUGHTER", Tier.INTERMEDIATE);
		put("MOURNINGS_END_PART_I", Tier.MASTER);
		put("MOURNINGS_END_PART_II", Tier.MASTER);
		put("MURDER_MYSTERY", Tier.NOVICE);
		put("MY_ARMS_BIG_ADVENTURE", Tier.EXPERIENCED);
		put("NATURE_SPIRIT", Tier.INTERMEDIATE);
		put("OBSERVATORY_QUEST", Tier.INTERMEDIATE);
		put("OLAFS_QUEST", Tier.INTERMEDIATE);
		put("ONE_SMALL_FAVOUR", Tier.EXPERIENCED);
		put("PANDEMONIUM", Tier.NOVICE);
		put("PERILOUS_MOONS", Tier.MASTER);
		put("PIRATES_TREASURE", Tier.NOVICE);
		put("PLAGUE_CITY", Tier.NOVICE);
		put("PRIEST_IN_PERIL", Tier.NOVICE);
		put("PRINCE_ALI_RESCUE", Tier.NOVICE);
		put("PRYING_TIMES", Tier.INTERMEDIATE);
		put("RAG_AND_BONE_MAN_I", Tier.NOVICE);
		put("RAG_AND_BONE_MAN_II", Tier.EXPERIENCED);
		put("RATCATCHERS", Tier.INTERMEDIATE);
		put("RECIPE_FOR_DISASTER", Tier.GRANDMASTER);
		put("RECIPE_FOR_DISASTER__ANOTHER_COOKS_QUEST", Tier.NOVICE);
		put("RECIPE_FOR_DISASTER__CULINAROMANCER", Tier.GRANDMASTER);
		put("RECIPE_FOR_DISASTER__EVIL_DAVE", Tier.EXPERIENCED);
		put("RECIPE_FOR_DISASTER__KING_AWOWOGEI", Tier.MASTER);
		put("RECIPE_FOR_DISASTER__LUMBRIDGE_GUIDE", Tier.EXPERIENCED);
		put("RECIPE_FOR_DISASTER__MOUNTAIN_DWARF", Tier.INTERMEDIATE);
		put("RECIPE_FOR_DISASTER__PIRATE_PETE", Tier.INTERMEDIATE);
		put("RECIPE_FOR_DISASTER__SIR_AMIK_VARZE", Tier.MASTER);
		put("RECIPE_FOR_DISASTER__SKRACH_UGLOGWEE", Tier.EXPERIENCED);
		put("RECIPE_FOR_DISASTER__WARTFACE__BENTNOZE", Tier.INTERMEDIATE);
		put("RECRUITMENT_DRIVE", Tier.NOVICE);
		put("REGICIDE", Tier.EXPERIENCED);
		put("ROMEO__JULIET", Tier.NOVICE);
		put("ROVING_ELVES", Tier.EXPERIENCED);
		put("ROYAL_TROUBLE", Tier.EXPERIENCED);
		put("RUM_DEAL", Tier.EXPERIENCED);
		put("RUNE_MYSTERIES", Tier.NOVICE);
		put("SCORPION_CATCHER", Tier.INTERMEDIATE);
		put("SCRAMBLED", Tier.INTERMEDIATE);
		put("SEA_SLUG", Tier.INTERMEDIATE);
		put("SECRETS_OF_THE_NORTH", Tier.MASTER);
		put("SHADES_OF_MORTTON", Tier.INTERMEDIATE);
		put("SHADOWS_OF_CUSTODIA", Tier.EXPERIENCED);
		put("SHADOW_OF_THE_STORM", Tier.INTERMEDIATE);
		put("SHEEP_HERDER", Tier.NOVICE);
		put("SHEEP_SHEARER", Tier.NOVICE);
		put("SHIELD_OF_ARRAV", Tier.NOVICE);
		put("SHILO_VILLAGE", Tier.INTERMEDIATE);
		put("SINS_OF_THE_FATHER", Tier.MASTER);
		put("SKIPPY_AND_THE_MOGRES", Tier.MINIQUEST);
		put("SLEEPING_GIANTS", Tier.INTERMEDIATE);
		put("SONG_OF_THE_ELVES", Tier.GRANDMASTER);
		put("SPIRITS_OF_THE_ELID", Tier.INTERMEDIATE);
		put("SWAN_SONG", Tier.MASTER);
		put("TAI_BWO_WANNAI_TRIO", Tier.INTERMEDIATE);
		put("TALE_OF_THE_RIGHTEOUS", Tier.INTERMEDIATE);
		put("TEARS_OF_GUTHIX", Tier.INTERMEDIATE);
		put("TEMPLE_OF_IKOV", Tier.INTERMEDIATE);
		put("TEMPLE_OF_THE_EYE", Tier.INTERMEDIATE);
		put("THE_ASCENT_OF_ARCEUUS", Tier.INTERMEDIATE);
		put("THE_BLOOD_MOON_RISES", Tier.GRANDMASTER);
		put("THE_CORSAIR_CURSE", Tier.INTERMEDIATE);
		put("THE_CURSE_OF_ARRAV", Tier.MASTER);
		put("THE_DEPTHS_OF_DESPAIR", Tier.INTERMEDIATE);
		put("THE_DIG_SITE", Tier.INTERMEDIATE);
		put("THE_ENCHANTED_KEY", Tier.MINIQUEST);
		put("THE_EYES_OF_GLOUPHRIE", Tier.INTERMEDIATE);
		put("THE_FEUD", Tier.INTERMEDIATE);
		put("THE_FINAL_DAWN", Tier.MASTER);
		put("THE_FORSAKEN_TOWER", Tier.INTERMEDIATE);
		put("THE_FREMENNIK_EXILES", Tier.MASTER);
		put("THE_FREMENNIK_ISLES", Tier.EXPERIENCED);
		put("THE_FREMENNIK_TRIALS", Tier.INTERMEDIATE);
		put("THE_FROZEN_DOOR", Tier.MINIQUEST);
		put("THE_GARDEN_OF_DEATH", Tier.INTERMEDIATE);
		put("THE_GENERALS_SHADOW", Tier.MINIQUEST);
		put("THE_GIANT_DWARF", Tier.INTERMEDIATE);
		put("THE_GOLEM", Tier.INTERMEDIATE);
		put("THE_GRAND_TREE", Tier.INTERMEDIATE);
		put("THE_GREAT_BRAIN_ROBBERY", Tier.EXPERIENCED);
		put("THE_HAND_IN_THE_SAND", Tier.INTERMEDIATE);
		put("THE_HEART_OF_DARKNESS", Tier.EXPERIENCED);
		put("THE_IDES_OF_MILK", Tier.NOVICE);
		put("THE_KNIGHTS_SWORD", Tier.INTERMEDIATE);
		put("THE_LOST_TRIBE", Tier.INTERMEDIATE);
		put("THE_PATH_OF_GLOUPHRIE", Tier.EXPERIENCED);
		put("THE_QUEEN_OF_THIEVES", Tier.INTERMEDIATE);
		put("THE_RED_REEF", Tier.EXPERIENCED);
		put("THE_RESTLESS_GHOST", Tier.NOVICE);
		put("THE_RIBBITING_TALE_OF_A_LILY_PAD_LABOUR_DISPUTE", Tier.NOVICE);
		put("THE_SLUG_MENACE", Tier.INTERMEDIATE);
		put("THE_TOURIST_TRAP", Tier.INTERMEDIATE);
		put("THRONE_OF_MISCELLANIA", Tier.EXPERIENCED);
		put("TOWER_OF_LIFE", Tier.NOVICE);
		put("TREE_GNOME_VILLAGE", Tier.INTERMEDIATE);
		put("TRIBAL_TOTEM", Tier.INTERMEDIATE);
		put("TROLL_ROMANCE", Tier.INTERMEDIATE);
		put("TROLL_STRONGHOLD", Tier.INTERMEDIATE);
		put("TROUBLED_TORTUGANS", Tier.EXPERIENCED);
		put("TWILIGHTS_PROMISE", Tier.INTERMEDIATE);
		put("UNDERGROUND_PASS", Tier.EXPERIENCED);
		put("VALE_TOTEMS", Tier.MINIQUEST);
		put("VAMPYRE_SLAYER", Tier.INTERMEDIATE);
		put("WANTED", Tier.INTERMEDIATE);
		put("WATCHTOWER", Tier.INTERMEDIATE);
		put("WATERFALL_QUEST", Tier.INTERMEDIATE);
		put("WHAT_LIES_BELOW", Tier.INTERMEDIATE);
		put("WHILE_GUTHIX_SLEEPS", Tier.GRANDMASTER);
		put("WITCHS_HOUSE", Tier.INTERMEDIATE);
		put("WITCHS_POTION", Tier.NOVICE);
		put("X_MARKS_THE_SPOT", Tier.NOVICE);
		put("ZOGRE_FLESH_EATERS", Tier.INTERMEDIATE);
	}
	public static Tier tierOf(Quest quest)
	{
		return TIERS.getOrDefault(quest.name(), Tier.INTERMEDIATE);
	}
	public static Rarity rarityOf(Quest quest)
	{
		return tierOf(quest).getRarity();
	}
}
